Offer functionality
appl-stock-project-org/appl-stock-project pull request #8
Opened 2024-02-09 12:34 UTC by Niklotin

Added end point for the offers

## Description

## Changes

## Notes

2024-02-12 18:11 UTC, tomb-cyber requested changes

2024-02-12 18:11 UTC, tomb-cyber commented on AppleStockAPI.Test/Properties/launchSettings.json
> +  "profiles": {
Is this from the old folder structure?

2024-02-12 18:11 UTC, tomb-cyber commented on AppleStockAPI.csproj.user
> +<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Is this from the old folder structure?

2024-02-12 18:11 UTC, tomb-cyber commented on AppleStockAPI/Properties/launchSettings.json
> +      "commandName": "Project",
Is this from the old folder structure?

2024-02-13 08:35 UTC, PaavoNykanen commented on AppleStockAPI/Controllers/OfferController.cs
> +            const double huijauHinta = 100;
Should use english in variable naming 😂

2024-02-13 08:37 UTC, PaavoNykanen commented on AppleStockAPI.Test/Properties/launchSettings.json
> +  "profiles": {
> Is this from the old folder structure?

After the tests were added I think we opted back to separating the API to its own folder so the tests can also be in their own folder.

2024-02-13 08:38 UTC, PaavoNykanen commented
Should probably also add some tests

2024-02-24 16:47 UTC, tomb-cyber commented on AppleStockAPI/Controllers/OfferController.cs
>              if (offer.Price <= highestValid && offer.Price >= lowestValid)
I realized that BidController has the same flaw, but this should probably also check that the offer has quantity set as at least 1.

2024-02-29 12:00 UTC, PaavoNykanen commented on AppleStockAPI/Controllers/OfferController.cs
> +            if (offerQuantity > 0) return true;
This could be simplified to just `return offerQuantity > 0`

2024-02-29 12:04 UTC, PaavoNykanen commented on AppleStockAPI/Controllers/OfferController.cs
> +            offer.Price = Math.Truncate(offer.Price * 100) / 100;
Could you use the same Math.round here instead? So like [here](https://github.com/appl-stock-project-org/appl-stock-project/blob/932576a99f62db08de13547133d6435745ccfcca/AppleStockAPI/Controllers/BidController.cs#L16) in bid controller

2024-02-29 12:12 UTC, PaavoNykanen commented on AppleStockAPI/Models/Offer.cs
> +        public DateTime OfferCreationTime { get; set; } = DateTime.Now;
Can we change the name of this attribute to `CreatedAt` to match the model of the bids [here](https://github.com/appl-stock-project-org/appl-stock-project/blob/932576a99f62db08de13547133d6435745ccfcca/AppleStockAPI/Models/Bid.cs#L14C25-L14C35)

2024-02-29 12:20 UTC, PaavoNykanen commented on AppleStockAPI.Test/OfferControllerTests.cs
> +            var offers = new List<Offer>();
Instead of creating a new offers list in every test you could add a `setUp` method like [here](https://github.com/appl-stock-project-org/appl-stock-project/blob/932576a99f62db08de13547133d6435745ccfcca/AppleStockAPI.Test/TradeControllerTests.cs#L16) and [here](https://github.com/appl-stock-project-org/appl-stock-project/blob/932576a99f62db08de13547133d6435745ccfcca/AppleStockAPI.Test/TradeControllerTests.cs#L11) which you can use in the tests. Then you could also add the `tearDown` method to clear the controller after every test like [here](https://github.com/appl-stock-project-org/appl-stock-project/blob/932576a99f62db08de13547133d6435745ccfcca/AppleStockAPI.Test/TradeControllerTests.cs#L22).

2024-02-29 12:22 UTC, PaavoNykanen commented on AppleStockAPI/Program.cs
> +List<Offer> offers = new List<Offer>();
I think the offers list should be inside the offerController as a private attribute like [here](https://github.com/appl-stock-project-org/appl-stock-project/blob/932576a99f62db08de13547133d6435745ccfcca/AppleStockAPI/Controllers/TradeController.cs#L12) in tradeController. This way you wouldn't need to pass it as an argument and I think having it inside the controller would make more sense for capsulation.

2024-02-29 13:23 UTC, Niklotin commented on AppleStockAPI/Controllers/OfferController.cs
> +            offer.Price = Math.Truncate(offer.Price * 100) / 100;
I could but Truncating leads to a more accurate end result due to double inaccuracy. For example if our cut-off range is at 90, and a payload with a price of 89.999 arrives to the handler, Math.Round rounds it up to 90 leading to a false-positive, while truncating the value leads to an expected result of just false. It's not a big deal, it's just a clumsy way of validating the payload data :D, can definitely change this.

2024-02-29 13:29 UTC, PaavoNykanen commented on AppleStockAPI/Controllers/OfferController.cs
> +            offer.Price = Math.Truncate(offer.Price * 100) / 100;
Yeah interesting point, it seems that truncating would actually be the correct way atleast in a real world scenario as you can't just round a users money :D In this project I'm fine with using either way, but lets just be consistent and use the same method in all of our price roundings. Truncating I guess would be the correct way so we could keep this and change the other controllers to also use truncation I think.

2024-03-02 23:43 UTC, tomb-cyber requested changes

2024-03-02 23:43 UTC, tomb-cyber commented on AppleStockAPI/Controllers/OfferController.cs
> +        public static Response HandleOffer(Offer offer, List<Offer> Offers)
Does this need the second parameter as the list is an instance variable? Also where do valid offers get added to the list?

2024-03-02 23:43 UTC, tomb-cyber commented on AppleStockAPI/Controllers/OfferController.cs
> +        public static bool CheckOffer(Offer offer, Response response)
Could this response instance be initiated in this function rather than in the HandleOffer. Wouldn't have to pass the second parameter

2024-03-03 10:39 UTC, Niklotin commented on AppleStockAPI/Controllers/OfferController.cs
> +        public static Response HandleOffer(Offer offer, List<Offer> Offers)
No it doesn't need the second parameter anymore, also oopsies on forgetting to actually add the offer into the list.

2024-03-03 10:44 UTC, Niklotin commented on AppleStockAPI/Controllers/OfferController.cs
> +        public static bool CheckOffer(Offer offer, Response response)
Absolutely could. Since changing the intiation of the response would shift function responsibilities, do you think it'd be better if handling and checking were to be done in one function instead?

2024-03-03 11:14 UTC, tomb-cyber commented on AppleStockAPI/Controllers/OfferController.cs
> +        public static bool CheckOffer(Offer offer, Response response)
I think this function is good, it makes the HandleOffer easier to read. I don't think it matters as a responsibility question where the response or the checking is, because the HandleOffer is anyways dependent on both. It just makes it more clean imo. Unless you can see a reason why we would need to initialize a Response object elsewhere and then modify it. But if the HandleOffer is the only place where we need this, then I think the slight responsibility change is fine.

2024-03-03 13:44 UTC, tomb-cyber requested changes

2024-03-03 13:44 UTC, tomb-cyber commented on AppleStockAPI.Test/OfferControllerTests.cs
>              Assert.AreEqual($"Offer succesful with the price of {offer.Price} and quantity of {offer.Quantity}", response.SuccessMessage);
I think in a test the expected string should not use the tested offer's properties, but the price and quantity should be constant/independent of the tested object. Because now if the HandleOffer logic is broken in a way that would set the offer object's price and quantity to 0, this test would still pass. This applies to all the tests

2024-03-03 13:44 UTC, tomb-cyber commented on AppleStockAPI/Program.cs
> +app.MapPost("/offer", (Offer payload) => { var offerController = new OfferController(); return offerController.HandleOffer(payload); });
I think now this will create a new offerList every time, so the added offers are always wiped.

2024-03-03 13:44 UTC, tomb-cyber commented on AppleStockAPI/Controllers/OfferController.cs
>              const double MOCKPRICE = 100;
Maybe not necessary now, but later on this class has to be changed, so that the stock price gets passed on to it, because storing the stock price won't be the responsibility of this class. This also means reworking the tests

2024-03-03 15:48 UTC, Niklotin commented on AppleStockAPI/Program.cs
> +app.MapPost("/offer", (Offer payload) => { var offerController = new OfferController(); return offerController.HandleOffer(payload); });
I thought so too, i did write a test for this(which i now realize i didn't push :D) where the list retained its values through multiple POST requests, but now that i think about it, it propably worked because the test keeps the list in scope so the list doesn't actually get garbage collected at any point, which it does when the app is actually running. I fix i fix nw.

2024-03-03 16:57 UTC, tomb-cyber commented on AppleStockAPI/Controllers/OfferController.cs
> +    public class OfferController
Is there a way to remove offers? The highest controller will have to remove offers and bids from their own lists once a trade is made. Also is there any tests that check that adding multiple offers in a row works, or what happens when valid and invalid once are added?

2024-03-05 10:20 UTC, PaavoNykanen approved these changes

2024-03-05 10:22 UTC, tomb-cyber approved these changes

2024-03-05 10:22 UTC, merged